name: Prod Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/ci.yaml
      - .github/workflows/deploy-dev.yaml
      - .vscode/**/*
      - test/**/*
      - .formatter.exs
      - .gitignore
      - README.md
      - docker-compose.yml
      - Makefile
      - config/dev.exs
      - config/test.exs

jobs:
  deploy:
    name: Deploy wrench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c fly.prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
